name: Build

on: [push]

jobs:
  Build:
    name: ${{ matrix.name }} - ${{ matrix.config}}|${{ matrix.architecture}}
    runs-on: ${{ matrix.os}}
    
    strategy:
      matrix:
        include:
        - { name: Windows (VS-2019), os: windows-2019, config: Release, architecture: x64}
        - { name: Windows (VS-2019), os: windows-2019, config: Release, architecture: Win32}
        - { name: Windows (VS-2019), os: windows-2019, config: Debug, architecture: x64}
        - { name: Windows (VS-2019), os: windows-2019, config: Debug, architecture: Win32}
        - { name: Windows (VS-2019), os: windows-2019, config: Release-Enduser, architecture: x64}
        - { name: Windows (VS-2019), os: windows-2019, config: Release-Enduser, architecture: Win32}
        
    steps:
    - uses: actions/checkout@v4.1.1
    
    - name: Build the external dependencies in "framework"
      if: matrix.os == 'windows-2019'
      run: .\framework\externel\build_externals_windows.bat

    - name: Build sonic3air + OxygenEngine
      if: matrix.os == 'windows-2019'
      uses: Elskom/build-dotnet@v1.1.1
      with:
        SOLUTION_FILE_PATH: .\Oxygen\sonic3air\build\_vstudio\sonic3air.sln

    - name: Upload Artifact
      uses: actions/upload-artifact@v3.1.3
      with:
        path: ./Oxygen/sonic3air
